# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT BOOT_FLASH CACHE STRING "Type of multi-context")
#-----------------------Build Boot Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Boot.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " Boot)
    ExternalProject_Add(STM32H7S78-DK-CoreMark_Boot
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/Boot/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/Boot
        PREFIX                      Boot
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    )
	set(ST_BOOT_FLASH_BOOT_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Boot/build/STM32H7S78-DK-CoreMark_Boot${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to boot project target")
endif()

